### ISSUE TITLE
[youtube] playlists page stopped working

### ISSUE THREAD

**Issue by pjta** [l1ving/youtube-dl#29]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.11.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v https://www.youtube.com/user/TheLinuxFoundation/playlists
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/user/TheLinuxFoundation/playlists']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.01.1
[debug] Python version 3.9.0 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlists] TheLinuxFoundation: Downloading webpage
[download] Downloading playlist: The Linux Foundation
[youtube:playlists] playlist The Linux Foundation: Downloading 0 videos
[download] Finished downloading playlist: The Linux Foundation
```
See: **Downloading 0 videos**

**Comment by ZenulAbidin** [comment]
From debugging, I think the `YoutubeEntryListBaseInfoExtractor` regex is broken. https://github.com/l1ving/youtube-dl/blob/8106dc7cd5770181cdf92ffa00850da2dceaa4bc/youtube_dl/extractor/youtube.py#L287, the regex for the Load More button in particular is not matching anything.

**Comment by ZenulAbidin** [comment]
An update: Adding that regex to `_update_pages` allows it to get the first 29 videos, when it tries to get the next page of videos it fails because the `_entries` regex has also become invalid. I'm currently looking for the new place in the webpage where the Load more ID is located.

Use `python tests/test_download.py TestDownloader.test_YoutubePlaylists_1` to reproduce this issue, the test should download 70 playlists, but with my changes it gets only 29 (and with a stock youtube_dl it won’t get any videos).

**Comment by apaloma** [comment]
I think this is broken again within the last few days. I only get the first page when downloading channels. Using the latest, 2020.12.02

**Comment by l1ving** [comment]
Ask in the official repo
